### ISSUE TITLE
请求支持新版的解密：HN8145V万兆光猫，在恢复华为原厂界面后，导出的配置文件中，加密方式变化

### ISSUE THREAD

**Issue by Mrcoolfuyu** [wx1183618058/HuaWei-Optical-Network-Terminal-Decoder#1]
配置文件如下：
```
 <UserInterface>

<X_HW_CLITelnetAccess Access="1" TelnetPort="23"/>
<X_HW_CLIUserInfo NumberOfInstances="1">
<X_HW_CLIUserInfoInstance InstanceID="1" Username="root" Userpassword="$2&lt;hXpUC}-5%k\fgU*o.Z),/yvUFT;J&apos;u2vLPPX$oK!&lt;iVJ[uzy@4n&apos;c=&quot;JDi+A}C7-X+-/@|D\T-&apos;o9FBSQNo4XU&lt;GMW6&gt;RXfwVN&amp;$" UserGroup="" ModifyPWDFlag="0" EncryptMode="2" Salt="7764c3e15ad4b3f8d3783025"/>
</X_HW_CLIUserInfo>
<X_HW_WebUserInfo NumberOfInstances="2">
<X_HW_WebUserInfoInstance InstanceID="1" UserName="useradmin" Password="$2T`b6E(}vTH6@,@LqY{A1V5j!3y,Yj!P83n82%CVD$" UserLevel="1" Enable="1" ModifyPasswordFlag="0" PassMode="2" Alias="cpe-1"/>
<X_HW_WebUserInfoInstance InstanceID="2" UserName="telecomadmin" Password="$2{oxs=`A^TY[&gt;,1);7WFZKm%0$_U=s%hjUJ/|)|;9Z^VTDfCoP1UH9z;aG3&apos;*&apos;CPk4NM1d)Xy\Z&apos;:rdg(;]FtT5M*O%tn11W&apos;=4&lt;/$" UserLevel="0" Enable="1" ModifyPasswordFlag="0" PassMode="3" Alias="cpe-2" Salt="c358d9e20afbab3bc6b0f32d"/>
</X_HW_WebUserInfo>
<X_HW_WebSslInfo Enable="0" CertPassword="$2OBl}0ODN\ReP=-&apos;XsOEW,kC~7::K8&quot;Hfs&quot;D&lt;n]JT$"/>
</UserInterface>
```
如上所示：
CLI用户root的密码未知，需解密；
useradmin的明文密码为ecvif，可用程序解密；
telecomadmin的明文密码为073p713u，加了salt，无法用原有程序解密。

如需任何协助，随时联系。

**Comment by wx1183618058** [comment]
把新版固件提取给我，有空的时候逆向看下。------------------ 原始邮件 ------------------
发件人: "Mrcool"<notifications@github.com>
发送时间: 2019年12月10日(星期二) 下午3:48
收件人: "wx1183618058/HuaWei-Optical-Network-Terminal-Decoder"<HuaWei-Optical-Network-Terminal-Decoder@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [wx1183618058/HuaWei-Optical-Network-Terminal-Decoder] 请求支持新版的解密：HN8145V万兆光猫，在恢复华为原厂界面后，导出的配置文件中，加密方式变化 (#1)



配置文&#x4EF6;如下：
 
 <X_HW_CLITelnetAccess Access="1" TelnetPort="23"/>
 <X_HW_CLIUserInfo NumberOfInstances="1">
 <X_HW_CLIUserInfoInstance InstanceID="1" Username="root" Userpassword="oK!<iVJ[uzy@4n'c="JDi+A}C7-X+-/@|D\T-'o9FBSQNo4XU<GMW6>RXfwVN&$" UserGroup="" ModifyPWDFlag="0" EncryptMode="2" Salt="7764c3e15ad4b3f8d3783025"/>
 </X_HW_CLIUserInfo>
 <X_HW_WebUserInfo NumberOfInstances="2">
 <X_HW_WebUserInfoInstance InstanceID="1" UserName="useradmin" Password="" UserLevel="1" Enable="1" ModifyPasswordFlag="0" PassMode="2" Alias="cpe-1"/> <X_HW_WebUserInfoInstance InstanceID="2" UserName="telecomadmin" Password="_U=s%hjUJ/|)|;9Z^VTDfCoP1UH9z;aG3''CPk4NM1d)Xy\Z':rdg(;]FtT5M*O%tn11W'=4</$" UserLevel="0" Enable="1" ModifyPasswordFlag="0" PassMode="3" Alias="cpe-2" Salt="c358d9e20afbab3bc6b0f32d"/>
 </X_HW_WebUserInfo>
 <X_HW_WebSslInfo Enable="0" CertPassword=""/>
 
 
部分用户的密码加了salt，请求作者更新~
 如需任何协助，随时联系。
 
&mdash;

**Comment by Gh-mean** [comment]
是否有解密方法？现在新版的hs8545v5也是这种加密了
