### ISSUE TITLE
Telnet密码解密后是MD5密文

### ISSUE THREAD

**Issue by xxhjkl** [wx1183618058/HuaWei-Optical-Network-Terminal-Decoder#2]
<X_HW_CLIUserInfo NumberOfInstances="1">
<X_HW_CLIUserInfoInstance InstanceID="1" Username="root" Userpassword="$2!fyaX{0NQ6UDmxHoq6DTY4yQOXAaw8ORj|~\2rr*fjJx)8W_X;w!i&amp;3EA@6Y$"/>
</X_HW_CLIUserInfo>
<X_HW_CLITelnetAccess Access="1" TelnetPort="23"/>

$2解密之后985a244ef129f7ea769df4971d95e84d，这个应该是md5密文，似乎网络上很多年了，大家解密后的密文都是这个，而md5无法逆运算，请问大佬可否放一个$2的逆运算的程序，可以把自己所需的密码加密成$2的密文再还原进去，以此达到破解telnet的目的。或者有没有办法调试出这个md5的明文。机器是HS8145C

**Comment by wx1183618058** [comment]
可以直接在管理界面内修改密码，所以不提供正向操作。
